# Generated by Django 5.2.5 on 2025-09-02 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mywork', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='Project_url',
            new_name='project_url',
        ),
    ]
