# Generated by Django 5.2.5 on 2025-09-05 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywork', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, choices=[('Python', 'Django & Flask'), ('Javascript', 'React, MERN, NEXT.JS'), ('Core', 'Custom CSS, JS & HTML'), ('design', 'UI/UX Design')], max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='featured',
            field=models.BooleanField(default=False, help_text='Feature this project on the homepage'),
        ),
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.CharField(blank=True, help_text='Comma-separated list of technologies used', max_length=200),
        ),
    ]
