# Generated by Django 5.2.5 on 2025-09-02 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywork', '0002_rename_project_url_project_project_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, upload_to='projects'),
        ),
    ]
